export const Channels = {
  bootstrap: 'prospero:bootstrap',
  ready: 'prospero:ready',
  createConversation: 'prospero:conversation:create',
  getConversation: 'prospero:conversation:get',
  deleteConversation: 'prospero:conversation:delete',
  renameConversation: 'prospero:conversation:rename',
  showContextMenu: 'prospero:context-menu',
  copyText: 'prospero:clipboard:copy',
  selectProvider: 'prospero:conversation:provider',
  chooseWorkspace: 'prospero:workspace:choose',
  attachFiles: 'prospero:files:attach',
  addScope: 'prospero:scope:add',
  removeScope: 'prospero:scope:remove',
  decideActionPlan: 'prospero:plan:decide',
  decideResearch: 'prospero:research:decide',
  saveWebSearch: 'prospero:web:configure',
  testWebSearch: 'prospero:web:test',
  openSource: 'prospero:source:open',
  sendTask: 'prospero:task:send',
  stopTask: 'prospero:task:stop',
  decidePermission: 'prospero:permission:decide',
  saveProvider: 'prospero:provider:save',
  deleteProvider: 'prospero:provider:delete',
  testProvider: 'prospero:provider:test',
  saveSettings: 'prospero:settings:save',
  event: 'prospero:event',
} as const;
